import { MigrationInterface, QueryRunner } from "typeorm";

export class AddingUserTable1763900970294 implements MigrationInterface {
    name = 'AddingUserTable1763900970294'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "role" varchar CHECK( "role" IN ('EMPLOYEE','HR','MANAGER','FINANCE','ADMIN') ) NOT NULL DEFAULT ('EMPLOYEE'), "is_active" boolean NOT NULL DEFAULT (1), "last_login" datetime, "failed_login_attempts" integer NOT NULL DEFAULT (0), "lock_until" datetime, "password_changed_at" datetime, "refresh_token" varchar, "employee_id" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_9760615d88ed518196bb79ea03d" UNIQUE ("employee_id"), CONSTRAINT "REL_9760615d88ed518196bb79ea03" UNIQUE ("employee_id"))`);
        await queryRunner.query(`CREATE TABLE "temporary_employees" ("id" varchar PRIMARY KEY NOT NULL, "emp_no" varchar NOT NULL, "name" varchar NOT NULL, "role" varchar NOT NULL, "bank_account" varchar NOT NULL, "base_salary" numeric NOT NULL, "join_date" date NOT NULL, "status" varchar NOT NULL DEFAULT ('ACTIVE'), "email" varchar NOT NULL, "department" varchar NOT NULL, "work_email" varchar NOT NULL, "personal_email" varchar NOT NULL, CONSTRAINT "UQ_2daea6572d4efff92ddc79ba7f9" UNIQUE ("emp_no"))`);
        await queryRunner.query(`INSERT INTO "temporary_employees"("id", "emp_no", "name", "role", "bank_account", "base_salary", "join_date", "status", "email", "department", "work_email", "personal_email") SELECT "id", "emp_no", "name", "role", "bank_account", "base_salary", "join_date", "status", emp_no || '@example.com', 'Default', emp_no || '@work.example.com', emp_no || '@personal.example.com' FROM "employees"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`ALTER TABLE "temporary_employees" RENAME TO "employees"`);
        await queryRunner.query(`CREATE TABLE "temporary_transactions" ("id" varchar PRIMARY KEY NOT NULL, "amount" numeric NOT NULL, "bank_ref" varchar, "status" varchar CHECK( "status" IN ('PENDING','PAID','FAILED') ) NOT NULL DEFAULT ('PENDING'), "attempts" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "payslip_id" varchar, "payrun_id" varchar, "employee_id" varchar, CONSTRAINT "FK_eeaf48e230619e81e05a327b5dc" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_df4412630fd075d6274a62d46ee" FOREIGN KEY ("payrun_id") REFERENCES "payruns" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_708ec3c97313bcf84bdb798b635" FOREIGN KEY ("payslip_id") REFERENCES "payslips" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transactions"("id", "amount", "bank_ref", "status", "attempts", "created_at", "payslip_id", "payrun_id", "employee_id") SELECT "id", "amount", "bank_ref", CASE WHEN "status" IN ('PENDING', 'PAID', 'FAILED') THEN "status" ELSE 'PENDING' END, "attempts", "created_at", "payslip_id", "payrun_id", "employee_id" FROM "transactions"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`ALTER TABLE "temporary_transactions" RENAME TO "transactions"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "role" varchar CHECK( "role" IN ('EMPLOYEE','HR','MANAGER','FINANCE','ADMIN') ) NOT NULL DEFAULT ('EMPLOYEE'), "is_active" boolean NOT NULL DEFAULT (1), "last_login" datetime, "failed_login_attempts" integer NOT NULL DEFAULT (0), "lock_until" datetime, "password_changed_at" datetime, "refresh_token" varchar, "employee_id" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_9760615d88ed518196bb79ea03d" UNIQUE ("employee_id"), CONSTRAINT "REL_9760615d88ed518196bb79ea03" UNIQUE ("employee_id"), CONSTRAINT "FK_9760615d88ed518196bb79ea03d" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_users"('id', 'email', 'password', 'role', 'is_active', 'last_login', 'failed_login_attempts', 'lock_until', 'password_changed_at', 'refresh_token', 'employee_id', 'created_at', 'updated_at') SELECT 'id', 'email', 'password', 'role', 'is_active', 'last_login', 'failed_login_attempts', 'lock_until', 'password_changed_at', 'refresh_token', 'employee_id', 'created_at', 'updated_at' FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "role" varchar CHECK( "role" IN ('EMPLOYEE','HR','MANAGER','FINANCE','ADMIN') ) NOT NULL DEFAULT ('EMPLOYEE'), "is_active" boolean NOT NULL DEFAULT (1), "last_login" datetime, "failed_login_attempts" integer NOT NULL DEFAULT (0), "lock_until" datetime, "password_changed_at" datetime, "refresh_token" varchar, "employee_id" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_9760615d88ed518196bb79ea03d" UNIQUE ("employee_id"), CONSTRAINT "REL_9760615d88ed518196bb79ea03" UNIQUE ("employee_id"))`);
        await queryRunner.query(`INSERT INTO "users"('id', 'email', 'password', 'role', 'is_active', 'last_login', 'failed_login_attempts', 'lock_until', 'password_changed_at', 'refresh_token', 'employee_id', 'created_at', 'updated_at') SELECT 'id', 'email', 'password', 'role', 'is_active', 'last_login', 'failed_login_attempts', 'lock_until', 'password_changed_at', 'refresh_token', 'employee_id', 'created_at', 'updated_at' FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "transactions" RENAME TO "temporary_transactions"`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" varchar PRIMARY KEY NOT NULL, "amount" numeric NOT NULL, "bank_ref" varchar, "status" varchar NOT NULL, "attempts" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "payslip_id" varchar, "payrun_id" varchar, "employee_id" varchar, CONSTRAINT "FK_eeaf48e230619e81e05a327b5dc" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_df4412630fd075d6274a62d46ee" FOREIGN KEY ("payrun_id") REFERENCES "payruns" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_708ec3c97313bcf84bdb798b635" FOREIGN KEY ("payslip_id") REFERENCES "payslips" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "transactions"('id', 'amount', 'bank_ref', 'status', 'attempts', 'created_at', 'payslip_id', 'payrun_id', 'employee_id') SELECT 'id', 'amount', 'bank_ref', 'status', 'attempts', 'created_at', 'payslip_id', 'payrun_id', 'employee_id' FROM "temporary_transactions"`);
        await queryRunner.query(`DROP TABLE "temporary_transactions"`);
        await queryRunner.query(`ALTER TABLE "employees" RENAME TO "temporary_employees"`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" varchar PRIMARY KEY NOT NULL, "emp_no" varchar NOT NULL, "name" varchar NOT NULL, "role" varchar NOT NULL, "bank_account" varchar NOT NULL, "base_salary" numeric NOT NULL, "join_date" date NOT NULL, "status" varchar NOT NULL DEFAULT ('ACTIVE'), CONSTRAINT "UQ_2daea6572d4efff92ddc79ba7f9" UNIQUE ("emp_no"))`);
        await queryRunner.query(`INSERT INTO "employees"('id', 'emp_no', 'name', 'role', 'bank_account', 'base_salary', 'join_date', 'status') SELECT 'id', 'emp_no', 'name', 'role', 'bank_account', 'base_salary', 'join_date', 'status' FROM "temporary_employees"`);
        await queryRunner.query(`DROP TABLE "temporary_employees"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
